# Generated by Django 5.0.4 on 2024-05-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="theatres",
            name="movies",
            field=models.ManyToManyField(to="movies.movies"),
        ),
    ]
